spring.application.name=nxtbus-backend

# application.properties

# Runtime queries — restricted role, used by Hibernate/JPA,(use when running with docker)
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# use when running in ide (it makes debuging and rebuilding faster)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/nxtbus_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:nxtbus_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:nxtbus_password}