spring.application.name=nxtbus-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/nxtbus_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:nxtbus_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:nxtbus_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info